/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventToken } from "./EventToken";
export type { TicketItem } from "./TicketItem";
export type { TicketsT } from "./TicketsT";
