/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { TicketItem } from "./TicketItem";
export type { TicketsT } from "./TicketsT";
